#:schema node_modules/wrangler/config-schema.json
name = "dd"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d12b5bfeb1bf46f69aa88aa248770f95" }
]

[assets]
directory = "./public"
